### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by SithLor** [dar-su/arc9_eft_57#2]
fix

![image](https://user-images.githubusercontent.com/84148006/211690357-7302976e-9ea7-4074-9f9a-06f9c7e77088.png)
![image](https://user-images.githubusercontent.com/84148006/211690392-a68308e3-b635-4161-b40f-4af1ee5625b1.png)

**Comment by SithLor** [comment]
it missing AR9EFT goblal

**Comment by dar-su** [comment]
You dumbass install shared https://github.com/Mal0-1471/arc9_eft_shared

**Comment by dar-su** [comment]
or just wait for release
it is really soon

**Comment by SithLor** [comment]
I was using work Verizon
