### ISSUE TITLE
Weapon jamming: Malicious function

### ISSUE THREAD

**Issue by UltraBlackLinux** [dar-su/arc9_eft_57#3]
No clue if this an arc9 issue, but whenever the weapon jams, I get a popup saying "Malicious Function Bolt Jammed"

Can you fix that?

**Comment by dar-su** [comment]
Are you fucking serious

**Comment by UltraBlackLinux** [comment]
yeah

**Comment by UltraBlackLinux** [comment]
no clue. Maybe I had a brainlag that day. It does in fact say malfunction
